name: Node.js CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.11.0]
    env:
      RESEND_API_KEY: ${{secrets.RESEND_API_KEY}}
      GMAIL_EMAIL_ADDRESS: ${{secrets.GMAIL_EMAIL_ADDRESS}}
      GMAIL_PASS: ${{secrets.GMAIL_PASS}}
      SPOTIFY_CLIENT_ID: ${{secrets.SPOTIFY_CLIENT_ID}}
      SPOTIFY_CLIENT_SECRET: ${{secrets.SPOTIFY_CLIENT_SECRET}}
      SPOTIFY_REFRESH_TOKEN: ${{secrets.SPOTIFY_REFRESH_TOKEN}}
      SPOTIFY_CODE: ${{secrets.SPOTIFY_CODE}}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Restart PM2
        run: pm2 restart ~/ecosystem.config.js
